# Site settings
title: Always an answer
email: emiliano.heyns@iris-advies.com
description: > # this means to ignore newlines until "baseurl:"
  Just random thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://retorquere.github.io" # the base hostname & protocol for your site
twitter_username: retorequere
github_username:  retorequere

# Build settings
markdown: kramdown
